### ISSUE TITLE
Criar Descrição de todos os Casos de Uso com o template (Nome; ator principal; descrição; pré-condição; caminho principal; caminhos alternativos; pós-condição; Adornos)

### ISSUE THREAD

**Issue by ic3K1ng** [ic3K1ng/Rooms-Equipments#12]

**Comment by anilhazar** [comment]
## I am willing to take the responsibility of explanation of the use cases of the Client

- Consultar horarios disponiveis
- Consultar tamanho das salas
- Reportar avarias de Equipamentos
- Pedido de orçamento

**Comment by ic3K1ng** [comment]
So I'll take  Use Case Diagrams:

-  Adicionar recurso
- Responder a notificações de avarias
- Reportar avarias de equipamentos

**Comment by janicehortabd** [comment]
Me responsabilizo  por fazer:
-Cancelar Reservas;
-Consultar as Reservas feitas;
-Elaborar Orçamento;

**Comment by dasilva-2024** [comment]
-Gerar relatórios de utilização de salas e equipamentos.
-Responder a pedido de reserva de salas e equipamento.
-Consultar notificações de avarias .

**Comment by dasilva-2024** [comment]
1. Gerar relatórios de utilização de salas e equipamentos.
2. Responder a pedido de reserva de salas e equipamento.
3. Consultar notificações de avarias .
